#!/bin/bash
set -x
REPO_FOLDER=${PWD}
WRISTBAND_ROOT_FOLDER=$REPO_FOLDER/wristband_simulation
BINARY_OUTPUT_FOLDER=$WRISTBAND_ROOT_FOLDER/build/libs
BINARY_OUTPUT_FILE=$BINARY_OUTPUT_FOLDER/WristbandEmulator-1.2.2-uber.jar
SETTINGS_PATHFOLDER=$REPO_FOLDER/settings
SETTINGS_PATHFILE_ORIGIN=$SETTINGS_PATHFOLDER/settingsApplication.conf
RELEASE_FOLDER=$REPO_FOLDER/Releases
VERSION_NEW="$1"
FILERELEASE_NAME=wristband_simulation_$VERSION_NEW.jar
SCRIPT_LAUNCH_BASHNAME=launch_$VERSION_NEW.sh
SETTINGS_DESTINATION_FILENAME=settingsApplication_$VERSION_NEW.conf

if [ -f $BINARY_OUTPUT_FILE ]; then
	cp $BINARY_OUTPUT_FILE $RELEASE_FOLDER/$FILERELEASE_NAME
	cp $SETTINGS_PATHFILE_ORIGIN $RELEASE_FOLDER/$SETTINGS_DESTINATION_FILENAME
	echo "java -jar $FILERELEASE_NAME $SETTINGS_DESTINATION_FILENAME" > $RELEASE_FOLDER/$SCRIPT_LAUNCH_BASHNAME
else
	echo "$BINARY_OUTPUT_FILE NOT FOUND!"
fi